### ISSUE TITLE
Should we also be  demoing npm deployment from travis here?

### ISSUE THREAD

**Issue by Joshua-Anderson** [travis-ci-examples/node.js#1]
Since this is a npm module, I think it would make sense to show show how travis can deploy to npm. The reason I'm not making a pull request is that most of the work involves encrypted keys for travis.You would have to add this to your .travis.yml:

```yml
language: node_js

# test on three node.js versions: 0.6 and 0.8 and 0.10
node_js:
  - 0.6
  - 0.8
  - 0.10
deploy:
  provider: npm
  email: ...
  api_key: ...
  on:
    branch: master
    node: 0.10
# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
notifications:
  irc: "irc.freenode.org#travis"
```
